-- Reemplazar contactos CC de ejemplo por lista real Avvale
DELETE FROM `cc_contacts`;

INSERT INTO `cc_contacts` (`id`, `name`, `email`, `created_at`) VALUES
(UUID(), 'Agustin Figueredo', 'agustin.figueredo@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Aitor Sanchez', 'aitor.sanchez@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Alejandra Castedo', 'alejandra.castedo@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Alfredo Perez', 'alfredo.perez@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Alvaro Arbaiza', 'alvaro.arbaiza@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Antonio Guzman', 'antonio.guzman@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Antonio Sanz', 'antonio.sanz@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Daniel Marchante', 'daniel.marchante@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Daniela Gonzalez', 'daniela.gonzalez@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'David Gonzalez Pacheco', 'david.gonzalezp@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'David Orozco Villarrubia', 'david.orozco@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'David Rodriguez-Barba Jimenez', 'david.rodriguezb@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Dionisio Garcia', 'dionisio.garcia@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Enrique Stampa García-Ormaechea', 'enrique.stampa@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Enrique Torres Barrasa', 'enrique.torres@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Fabio Caroli', 'fabio.caroli@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Francisco Javier Lopez Crespo', 'javier.lopez@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Gerard Prats Ramirez', 'gerard.prats@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Giovanny Buitrago', 'giovanny.buitrago@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Guillermo Truan', 'guillermo.truan@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Ignacio Hidalgo Pitto', 'ignacio.hidalgo@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Irene Dieguez', 'irene.dieguez@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Isabella Josefina Santoro Lombardo', 'isabella.santoro@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Ismael Bermejo Jimenez', 'ismael.bermejo@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Javier Arozarena Garcia', 'javier.arozarena@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Javier Martinez Llaguno', 'javier.llaguno@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Joanandreu Blade', 'joanandreu.blade@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Jose Javier Rigal Martinez', 'javier.rigal@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Jose Manuel Nieto Navarro', 'josemanuel.nieto@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'José Manuel Prieto Sanz', 'josemanuel.prieto@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Jose Manuel Romero Martinez', 'josemanuel.romero@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Jose Ramon Dominguez Rodriguez', 'joseramon.dominguez@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Juan Carlos Fuentes Rubio', 'juancarlos.fuentes@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Juan Carlos Vidaller Lasierra', 'juancarlos.vidaller@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Juan Pablo Guichon', 'juanpablo.guichon@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Luis Zarzo Fuertes', 'luis.zarzo@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Manuel Angel Garcia Sanchez', 'manuelangel.garcia@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Manuel Jesús Pacheco Ibáñez', 'manuel.pacheco@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Manuel Torres Brabo', 'manuel.torres@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Marc Pla Simon', 'marc.pla@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Maria Gonzalez Abarca', 'maria.gonzalez@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Mario Cortes Flores', 'mario.cortesf@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Mario Morillo Molinuevo', 'mario.morillo@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Oscar Garcia Garcia', 'oscar.garcia@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Pablo Virseda', 'pablo.virseda@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Rafael Garcia Montserrat', 'rafael.garcia@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Raquel Mera Manteca', 'raquel.mera@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Roberto Fernandez Revilla', 'roberto.fernandez@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Rodrigo Lázaro Murillo', 'rodrigo.lazaro@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Rosa Sanchez', 'rosa.sanchez@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Sergio Arrogante Gomez', 'sergio.arrogante@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Silvia Rodríguez González', 'silvia.rodriguez@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Sonia Amatlle', 'sonia.amatlle@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Vanesa Domenech Alonso', 'vanesa.domenech@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Veronica Viveros Sugrañez', 'veronica.viveros@avvale.com', CURRENT_TIMESTAMP(3)),
(UUID(), 'Xavier Tor Barutel', 'xavier.tor@avvale.com', CURRENT_TIMESTAMP(3));
