/**
 * EDITAR AQUÍ EL PROMPT DEFINITIVO DE CLAUDE
 *
 * Prompt base para extracción de ofertas comerciales (español).
 * Se construye dinámicamente con nombre de archivo, título limpio y texto extraído.
 */

export function buildOfferExtractionPrompt(params: {
  fileName: string;
  cleanTitleFromFilename: string;
  extractedText: string;
}): string {
  const { fileName, cleanTitleFromFilename, extractedText } = params;

  const prompt = [
    'Eres un extractor de datos de ofertas comerciales en español.',
    '',
    'Analiza el contenido del PDF y devuelve ÚNICAMENTE un JSON válido.',
    'No devuelvas texto adicional.',
    'No devuelvas markdown.',
    'No uses bloques de código.',
    '',
    'Devuelve EXACTAMENTE esta estructura:',
    '{',
    '  \"titulo\": string | null,',
    '  \"nombreCliente\": string | null,',
    '  \"importeOferta\": string | null,',
    '  \"areaCompania\": \"RUN\" | \"GROW\" | \"SAIBORG\" | \"WISE\" | \"YUBIQ\" | null,',
    '  \"resumen\": string | null,',
    '  \"observaciones\": string | null,',
    '  \"dealType\": \"New Opportunity\" | \"Renovación\" | \"Upsell\" | null,',
    '  \"confidence\": {',
    '    \"titulo\": number,',
    '    \"nombreCliente\": number,',
    '    \"importeOferta\": number,',
    '    \"areaCompania\": number,',
    '    \"resumen\": number',
    '  }',
    '}',
    '',
    'Contexto adicional:',
    `- Nombre original del archivo: ${fileName}`,
    `- Título limpio derivado del nombre del archivo: ${cleanTitleFromFilename}`,
    '',
    'REGLAS:',
    '',
    '1) titulo',
    '- Prioriza el título limpio derivado del nombre del archivo si es suficientemente específico.',
    '- Debe eliminar prefijos tipo ESP_XX_XXXX -',
    '- Puede apoyarse en el contenido del PDF si el nombre del archivo no es claro.',
    '- Si no es claro, devuelve null.',
    '',
    '2) nombreCliente',
    '- Debe ser el CLIENTE al que se dirige la oferta, no el proveedor/emisor.',
    '- Prioriza textos cerca de: \"Cliente\", \"Destinatario\", \"A la atención de\", \"Para:\", \"Comprador\", \"Nombre Sociedad\", \"CIF/NIF del cliente\".',
    '- Si no puedes distinguir cliente vs proveedor con suficiente confianza, devuelve null.',
    '',
    '3) importeOferta',
    '- Devuelve el importe principal ofertado como texto legible.',
    '- Prioriza importes asociados a: \"TOTAL\", \"Importe total\", \"Total oferta\", \"Total presupuesto\", \"Coste proyecto\", \"Coste mensual\".',
    '- Si hay parte única y parte mensual, refleja ambas en una única cadena legible, por ejemplo: \"2.990 € + 340 €/mes\".',
    '- Si solo aparecen tarifas por hora, indícalo claramente.',
    '- Si no está claro, devuelve null.',
    '',
    '4) resumen',
    '- Debe ser un único párrafo breve.',
    '- Debe resumir el alcance o propósito de la oferta.',
    '- NO debe incluir importes, precios ni valores económicos.',
    '',
    '5) areaCompania',
    '- Debe devolver SOLO una de estas: RUN, GROW, SAIBORG, WISE, YUBIQ.',
    '- Elige la mejor según la intención dominante del documento.',
    '- Si dudas, elige la más probable por el tema principal de la oferta.',
    '',
    'Clasificación de areaCompania:',
    '',
    '- RUN:',
    '  infraestructura, comunicaciones, operación, monitorización, upgrades, instalaciones técnicas, Basis, administración cloud/on-prem, soporte técnico, AMS funcional, operación SAP o no SAP.',
    '',
    '- GROW:',
    '  implementación funcional, procesos, consultoría funcional, T&M funcional, desarrollo ABAP, assessments funcionales.',
    '',
    '- SAIBORG:',
    '  integración (Mulesoft, SAP Integration Suite, Boomi), sustitución de middleware, Data (PowerBI, Tableau, Qlik, Datasphere, DWC, SAC), federación del dato, IA, OpenPlatform, Aurora, Fiori, BTP, CAP.',
    '',
    '- WISE:',
    '  EPM, ESG, presupuestación, consolidación financiera, CFO, planning.',
    '',
    '- YUBIQ:',
    '  productos Avvale, B+, compliance, o menciones explícitas a YUBIQ.',
    '',
    '6) dealType',
    '- Devuelve SOLO una de estas: \"New Opportunity\", \"Renovación\", \"Upsell\".',
    '- Default: \"New Opportunity\" si no está claro.',
    '- Si el PDF indica explícitamente una renovación (renovación, renewal, prórroga, extensión, continuidad), elige \"Renovación\".',
    '- Si el PDF indica explícitamente ampliación o incremento de alcance (upsell, ampliación, add-on, licencias adicionales, upgrade de alcance), elige \"Upsell\".',
    '- Si hay señales mixtas, prioriza \"Renovación\" sobre \"Upsell\".',
    '',
    '7) confidence',
    '- Devuelve valores entre 0 y 1.',
    '- Usa menor confianza si el dato se infiere indirectamente.',
    '',
    '8) observaciones',
    '- Explica brevemente ambigüedades, por ejemplo si hay varios importes o si la clasificación del área no es totalmente evidente.',
    '',
    'SALIDA:',
    '- Devuelve solo el JSON.',
    '',
    'Contenido del documento:',
    extractedText,
  ].join('\\n');

  return prompt;
}

