/**
 * Criterios de línea Avvale alineados con `avvaleAreas` en la síntesis RFQ
 * (`rfq-synthesis-prompt.ts`) y con la pestaña KYC «Presencia por línea» (`solution_presence`).
 */

export const AVVALE_PRESENCE_SLUGS_ORDER = ['grow', 'run', 'wise', 'yubiq', 'saiborg', 'axazure'] as const;

/** Viñetas de clasificación (mismo texto de negocio que en RFQ). */
export const AVVALE_SOLUTION_LINE_CLASSIFICATION_BULLETS = `
  · RUN: infraestructura; hyperscalers (Google Cloud, AWS, Azure); Avvale Cloud Platform; administración y operación de sistemas SAP y no SAP; modelos OaaS, IaaS y PaaS; operación recurrente del landscape (on-prem, cloud privado, hyperscaler o híbrido): Basis / administración técnica SAP y no SAP, instalación y parcheo, upgrades técnicos (EHP, stacks), migraciones de sistema «lift» o rehosting sin rediseño funcional mayor, alta disponibilidad, backup y recuperación, DR, monitorización APM y observabilidad, gestión de incidentes y capacidad, redes y conectividad corporativa, ciberoperación de infra (firewalls, WAF operados), AMS técnico o AMS funcional centrado en estabilidad y evolutivos acotados, soporte 24x7, finops operativo ligado a explotación. **Migraciones a Azure (u otro hyperscaler), hosting, landing zone, plataforma o explotación «de Azure»** que **no** tengan como protagonista explícito Dynamics 365, Business Central o F&O como **aplicación de negocio** del encargo → **RUN**, no AXAZURE. Si el núcleo es «mantener en marcha y optimizar coste/riesgo», suele ser RUN.
  · GROW: proyectos de cambio funcional o de implantación; soporte funcional SAP en modalidad T&M; roll-out / greenfield / brownfield de módulos o soluciones (ERP, CRM, sectorial), rediseño de procesos, blueprint, fit-gap, localización legal, gestión del cambio y formación funcional, assessments de madurez de negocio, T&M o fixed price orientados a resultado funcional, desarrollo ABAP / extensions clásicas ligadas a requisitos de negocio, preparación de cutover funcional, migración maestros/transaccionales desde perspectiva funcional. Si el núcleo es «transformar o desplegar cómo trabaja el negocio», suele ser GROW.
  · SAIBORG: MuleSoft, Boomi, SAP Integration Suite / CPI / API Management, Kafka, event mesh, EDI/B2B; IA aplicada (copilots, asistentes, ML en procesos); SAP Datasphere; BDC (Business Data Cloud) cuando encaje en integración/datos de plataforma; BTP (Extension Suite, CAP, side-by-side); desarrollo de aplicaciones SAP y no SAP; RPA e hiperautomatización (incl. UiPath, orchestration); API-first, federación y gobierno del dato, data products, lakehouse / ingesta / calidad ligados a integración o productización de datos, analytics operativas (Power BI, Tableau) como capa de producto o self-service corporativo, SAC analítico no dominado por CFO group close, Fiori / UX enterprise, OpenPlatform u ofertas de producto software propias en ese espectro. Si el núcleo es «conectar, exponer datos/servicios o automatizar con plataforma», suele ser SAIBORG.
  · WISE: oferta orientada a CFO / office of finance: EPM y corporate performance (Group Reporting, consolidación, reporting regulatorio), planning, budgeting & forecasting, simulaciones, tax provisioning y reporting fiscal de grupo, treasury analytics, profitability y cost management, sostenibilidad y reporting ESG financiero-regulatorio (CSRD, métricas financieras de sostenibilidad) cuando el foco es reporting de dirección y no solo BI operativo. Si el núcleo es «cerrar, planificar y gobernar las cifras de empresa / grupo», suele ser WISE.
  · YUBIQ: soluciones de compliance; factura electrónica; producto y línea B+; identidad digital, acceso y privilegios (CIAM, IAM, SSO), experiencia de cliente o ciudadano (portales, onboarding digital), medios de pago, pasarelas y orquestación de pagos, compliance normativo del ciclo order-to-cash / procure-to-pay digital, antifraude y confianza, propuestas explícitas de la línea YUBIQ y compliance digital asociado. Si el núcleo es «confianza, identidad, pago o canal digital regulado», suele ser YUBIQ.
  · AXAZURE: **solo** la línea **Microsoft Business Applications** cuando el encargo gira en torno a **Dynamics 365** (Sales, Customer Service, Field Service, Marketing, Customer Insights), **ERP Microsoft** (Finance & Operations / F&O, Supply Chain Management, **Business Central**) o **Power Platform** (Power Apps, Power Automate, Power Pages, Dataverse, Copilot Studio) **como productos de negocio protagonistas**: implantación, roll-out, upgrade funcional-técnico sobre esas soluciones, AMS centrado en ellas, integraciones típicas del stack (p. ej. Dual-write, Dataverse ligado a D365). **No** asignes AXAZURE por **migración genérica a Azure**, **hosting**, **landing zone**, **IaaS/PaaS de infra** u operación de plataforma si el relato no ancla un **D365 / BC / F&O** (u oferta equivalente de negocio Microsoft) como núcleo del trabajo: eso corresponde a **RUN**. Tampoco uses AXAZURE solo por Microsoft 365 genérico (correo, Teams sin proyecto D365/Power Platform) ni por BI aislado sin Dynamics protagonista. Si el núcleo es «**Dynamics / BC / F&O / Power Platform de negocio** como protagonista», suele ser AXAZURE.`.trim();
